# 提示文本
message:
  prefix: "&c每日折扣 &f"
  help:
    default:
      - "&c每日折扣"
      - "&f/ds open <view> &e查看今日折扣商品"
    admin:
      - "&c每日折扣"
      - "&f/ds open <view> [玩家] &e查看今日折扣商品"
      - "&f/ds reset &e重置今日全服限购数"
      - "&f/ds resetPlayer &e重置玩家今日商品"
      - "&f/ds reload &e重置插件配置文件"
  not-exist: "该商品不存在!"
  limit:
    oneself: "今日购买已达上限."
    all: "该商品已经被抢光啦."
  pls-enter-player-name: "请输入玩家名字."
  player-offline: "玩家不在线."
  lack: "你没有足够的货币购买这个商品."
  denied: "你无法购买这个商品."
  buy: "&a成功购买折扣商品 &f%item%"
  reset: "成功重置当日商品."
  resetPlayer: "成功重置玩家 &a%player% &f当日商品."
  reload: "插件配置重载完成."